const express = require("express")
const router = express.Router()

const authRoutes = require("./Auth/auth.routes")
const userManagementRoutes = require("./UserManagement/userManagement.routes")
const companyManagementRoutes = require("./CompanyManagement/companyManagement.routes")
const jobCategoryRoutes = require("./JobCategory/jobCategory.routes")
const jobSubCategoryRoutes = require("./JobSubCategory/jobSubCategory.routes")
const skillsRoutes = require("./Skills/skills.routes")
const jobManagementRoutes = require("./JobManagement/JobManagement.routes")
const subscriptionRoutes = require("./Subscription/subscription.routes")
const internManagementRoutes = require("./InternManagement/internManagement.routes")
const supportRoutes = require("./Support/support.routes")
const candidateManagementRoutes = require("./CandidateManagement/candidateManagement.routes")
const resumeBankRoutes = require("./ResumeBank/resumeBank.routes")
const adminRoutes = require("./Admin/admin.routes")
const companyDashboardRoutes = require("./CompanyDashboard/companyDashboard.routes")
const exploreInternshipRoutes = require("./ExploreInternship/exploreInternship.routes")
const jobAlertRoutes = require("./JobAlert/jobAlert.routes")
const internAuthRoutes = require("./InternAuth/internAuth.routes")
const companyAuthRoutes = require("./CompanyAuth/companyAuth.routes")
const locationRoutes = require("./Locations/location.routes")
const notificationRoutes = require("./Notifications/notification.routes")
const internDashboardRoutes = require("./InternDashboard/internDashboard.routes")
const homeRoutes = require("./Home/home.routes")
const internNotificationRoutes = require("./InternNotifications/internNotifications.routes")
const blogCategoryRoutes = require("./BlogCategory/blogCategory.routes")
const blogTagRoutes = require("./BlogTags/blogTags.router")
const blogsRoutes = require("./Blogs/blogs.routes")
const contactUsRoutes = require("./ContactUs/contactUs.routes")
const internRegistrationRoutes = require("./InternRegistrationV5/internRegistration.routes")
const interviewRoutes = require("./Internview/interview.routes")
const aiInterviewRoutes = require("./AIInterview/aiInterview.routes")
const aiInterviewXRoutes = require("./AIInterview/aiInterviewX.routes")
const internSubscriptionRoutes = require("./InternSubscription/internSubscription.routes")
const aiCallRoutes = require("./AICall/aiCall.routes");
    

router.use("/interview", interviewRoutes)
router.use("/ai-interview", aiInterviewRoutes)
router.use("/ai-interview-x", aiInterviewXRoutes)
router.use("/intern-subscription", internSubscriptionRoutes)
router.use("/intern-registration", internRegistrationRoutes)
router.use("/contact-us", contactUsRoutes)
router.use("/blogs", blogsRoutes)
router.use("/blog-tag", blogTagRoutes)
router.use("/blog-category", blogCategoryRoutes)
router.use("/intern-notification", internNotificationRoutes)
router.use("/home", homeRoutes)
router.use("/intern-dashboard", internDashboardRoutes)
router.use("/auth", authRoutes)
router.use("/users", userManagementRoutes)
router.use("/company", companyManagementRoutes)
router.use("/job-category", jobCategoryRoutes)
router.use("/job-subCategory", jobSubCategoryRoutes)
router.use("/skills", skillsRoutes)
router.use("/jobs", jobManagementRoutes)
router.use("/subscription", subscriptionRoutes)
router.use("/interns", internManagementRoutes)
router.use("/support", supportRoutes)
router.use("/candidate", candidateManagementRoutes)
router.use("/resume-bank", resumeBankRoutes)
router.use("/admin", adminRoutes)
router.use("/company-dashboard",companyDashboardRoutes)
router.use("/explore-internship", exploreInternshipRoutes)
router.use("/job-alert", jobAlertRoutes)
router.use("/intern",internAuthRoutes)
router.use("/company-auth", companyAuthRoutes)
router.use("/location", locationRoutes)
router.use("/notification", notificationRoutes)
router.use("/ai-call", aiCallRoutes);

module.exports = router